### PR TITLE
Making suggestions

### PR DESCRIPTION
**Pull request by oliverbarnes**
Working on top of #29 (all commits were squashed into one).

Following (somewhat) the structure proposed [on this tute](http://balinterdi.com/2014/02/26/a-common-resource-route-pattern-in-ember-dot-js.html).

Also got stuck on creating the record for suggestion and associating it with the parent initiative. Looks like there's an [ember data bug](http://discuss.emberjs.com/t/ember-data-fixture-adapter-saving-record-loses-has-many-relationships/2821/6) that might be at play here. Tried adding a hack in an initializer, but nothing it. Royal PITA :P

On the bright side, the routing makes sense now, and once we can get the suggestion / initiative association saving, it should be easy to get the listing going after that. Hopefully :)

### CODE REVIEW

**Comment by oliverbarnes** [comment]
Pushing `suggestion` into `initiative` works now that it's done after `suggestion` is saved. Axed  `setupController` in favor of a separate `SuggestionsIndexController`, wiring it to `initiative` through `needs:`. Suggestion listing doesn't render yet though. Will continue on Monday. @locks, valeu a ajuda de novo ;)

**Comment by locks** [comment]
Any time :+1:

**Comment by oliverbarnes** [comment]
Finally got it working! SuggestionsRoute had to be renamed SuggestionsIndexRoute. Don't even need a SuggestionsController, it gets generated implicitly. Going to squash commits and merge

**Comment by Qianfinland** [comment]
great :)

**Comment by KatiRG** [comment]
great!!!

**Comment by KatiRG** [comment]
why is the template for the /initiatives/:initiative_id page located in
`templates/initiative.emblem` and not initiative/index.emblem as given in
the /#Routes tree in the ember debugger?

**Comment by oliverbarnes** [comment]
it's matching the parent InitiativeRoute, not InitiativeIndexRoute. and it's working fine

**Comment by KatiRG** [comment]
there is another `initiative.emblem` in `templates/initiatives/initiative.emblem` that appears redundant...

**Comment by oliverbarnes** [comment]
ohh it's a duplicate, a temp file that got mixed in the commits. it can be deleted, thanks for the catch

**Comment by KatiRG** [comment]
also there is something weird with the storage of suggestions...the user-typed suggestions get duplicated...

**Comment by oliverbarnes** [comment]
seems to be test-specific, when testing manually it saves a single one. I'm using find('.suggestion').first().text() to get around this for now.

**Pull request closed without merging**
