### PR TITLE
Listing initiatives

### PR DESCRIPTION
**Pull request by KatiRG**
Listing initiatives works. Test passes.

### CODE REVIEW

**Comment by KatiRG** [comment]
> stored in FIXTURES works and test passes. Should I also display initiatives created on the fly by the user?

CORRECTION: initiatives stored in FIXTURES and initiatives created on the fly by the user are displayed in /initiatives. Do you want to merge or should I rebase wrt your master?

**Comment by oliverbarnes** [comment]
Thanks @KatiRG. I think the easiest way to merge will be for you to start a new branch from latest master, and copy and paste just the specific stuff for the listing. No need for the ember-data production stuff, btw. Once you do that, send another request please, and I'll comment. About the fixtures vs initiatives created by the user, I don't think it's an issue, but you can walk through the steps on the test - asserting existing listed items, then adding a new initiative by filling out the form.

**Comment by KatiRG** [comment]
These tests fail:

not ok 2 PhantomJS 1.9 - Making a suggestion to an initiative Successfully
not ok 3 PhantomJS 1.9 - Making a suggestion to an initiative "after each" hook
not ok 8 PhantomJS 1.9 - Supporting an initiative "after each" hook

There is something weird with the suggestions data (even on master branch)--the suggestions typed in by the user get duplicated (see Data in ember debugger)

**Comment by oliverbarnes** [comment]
Closing the pull request - start a new brand new branch from latest master, then add the initiatives listing code (just the bare minimum) and test there, manually (no merge).

**Comment by KatiRG** [comment]
Done (https://github.com/oliverbarnes/participate-frontend/pull/36)

**Pull request closed without merging**
