### PR TITLE
Got Tests to Run with Mocha.

### PR DESCRIPTION
**Pull request by WMeldon**
So the issue was that there were various failures that `ember test` wasn't letting you know about.  

The first (and easiest) was just a 404 on the sinon-chai file.  Just needed to add another bit to the Brocfile. I also switched over to using a built version of sinon as the main repo doesn't come prebuilt.  

The final issue, which was the real cause of your woes, was that you were trying to use the BDD style of Mocha and I never got around to porting that bit.  I only ever did the TDD style (see [this](http://visionmedia.github.io/mocha/#interfaces)).  

That last bit is the reason I never actually released my ember-mocha forks.  I just never got them all fully functional, just the bare minimum to prove it could be done.  

**Edit**
One last thing, I also removed the `require('chai')` as I believe that test are also going to use ES6 modules (ie `import Chai from 'chai'`) though I don't know if they support that so you'll probably just be best off sticking with Globals for now.

### CODE REVIEW

**Comment by oliverbarnes** [comment]
Many thanks @WMeldon, this is more than I had hoped for :) All makes sense, I'll stick to TDD style til the add-on comes out

**Comment by chrmod** [comment]
Do you have any idea how to use `describe` syntax ?

**Comment by WMeldon** [comment]
@chrmod It's mainly an related to [ember-quit](https://github.com/rpflorence/ember-qunit).  I don't think it would too difficult to add, but I just never got around to it.  I changed it to `suite` [here](https://github.com/WMeldon/ember-qunit/blob/8109322c2d49ff74e1c7dd121639d658a56464f4/lib/module-for.js#L61).

**Comment by oliverbarnes** [comment]
@WMeldon visit() doesn't get recognized

```
not ok 1 PhantomJS 1.9 - Posting an initiative Successfully
    ---
        message: >
            Can't find variable: visit
        stack: >
            ReferenceError: Can't find variable: visit
                at :8
                at invoke (http://localhost:7357/assets/adapter-qunit.js:59)
                at http://localhost:7357/assets/adapter-qunit.js:97
                at http://localhost:7357/assets/mocha.js:4323
                at http://localhost:7357/assets/mocha.js:4724
                at http://localhost:7357/assets/mocha.js:4815
                at next (http://localhost:7357/assets/mocha.js:4649)
                at http://localhost:7357/assets/mocha.js:4659
                at next (http://localhost:7357/assets/mocha.js:4597)
                at http://localhost:7357/assets/mocha.js:4626
                at timeslice (http://localhost:7357/assets/mocha.js:5733)
```

**Comment by WMeldon** [comment]
@oliverbarnes First thing that comes to mind is `startApp()` not getting called.  

There is an [example acceptance test](https://github.com/WMeldon/ember-cli-todos/blob/mocha-compat/tests/acceptance/todos-test.js) that shows what needs to happen for the test helpers to get injected.  Could be something new though.

**Comment by oliverbarnes** [comment]
thanks @WMeldon, that was it. I saw those imports and assumed unrelated to the helpers :P lots to learn...

**Pull request merged**
