### PR TITLE
WIP 'me' (current user)

### PR DESCRIPTION
**Pull request by oliverbarnes**
Almost there, stuck figuring out how to fetch singular resources with ember-jsonapi-resources. Opened an [issue about it](https://github.com/pixelhandler/ember-jsonapi-resources/issues/26) on their repo.

@williamcodes @BernardTolosajr feedback welcome on the naming. I agonized over using 'me', 'currentUser' or 'currentParticipant', ended up just going with the simplest. 'current*' names get cumbersome naming routes, models and such.

### CODE REVIEW

**Comment by oliverbarnes** [comment]
Fetching 'me' resource now works after patching up EJR. Using our fork until PR gets approved. Also, this is working against the `get-me-and-participant-model` branch from oliverbarnes/participate-api#19

**Comment by williamcodes** [comment]
What does the `current` variable contain? Is it normally a `User` model, a `Participant` model, or something else? As much as I like the brevity of `current`, I think it's vague. I'd prefer `current_participant` if it contains a `Participant` model or `current_user` if it contains a `User` model. Just my two cents.

**Comment by BernardTolosajr** [comment]
current_participant or current_user looks straightforward. maybe lets called it "participant" or "user " model.  Something like this https://github.com/BernardTolosajr/participate/blob/feature-current-user/app/sessions/custom.js 

Then the backend just spit /participants or /users

**Comment by oliverbarnes** [comment]
@williamcodes I meant 'current_*', meaning current_user or current_participant. They'd have to be their own models on ember's side, since it has its own resource coming from the server. On the server the resource is a Participant model object, accessed as current_participant. The PR on the API app has more details.

@bernardtolosajr what would be the downsides for 'me', which is already implemented here?

**Comment by BernardTolosajr** [comment]
@oliverbarnes my bad i overlook the 'me' is currently implemented in the backend :)

**Comment by oliverbarnes** [comment]
No worries :)

**Comment by oliverbarnes** [comment]
What's left to work out is saving it to the session, if you want to take a
look

**Pull request merged**
