### PR TITLE
WIP: Initiative issue

### PR DESCRIPTION
**Pull request by oliverbarnes**
Kind of hacky, but working. Just working out a test kink.

Using `this.controller.content` to access what's submitted by the form, cause passing an object to the submit action, which is the way shown on EasyForm examples, doesn't work for me.

Haven't found a way to nest models with EasyForm, so the form has issue fields as initiative attributes ('issue_title', 'issue_description').

@KatiRG @Qianfinland feel free to ask questions in the comments

### CODE REVIEW

**Comment by KatiRG** [comment]
About passing an object to the submit action, do you mean doing something like `object.save()` as in this example https://gist.github.com/aloysius-lim/c793c1383fb17e3f4410 line 103?

**Comment by KatiRG** [comment]
By nested models, do you mean models that both `belongTo` each other? 

```
var Initiative = DS.Model.extend(Ember.Validations.Mixin, {
  title: DS.attr('string'),
  description: DS.attr('string'),
  isSupported: DS.attr('boolean'),
  issue: DS.belongsTo('issue'),
```

```
var Issue = DS.Model.extend(Ember.Validations.Mixin, {
  title: DS.attr('string'),
  description: DS.attr('string'),
  initiative: DS.belongsTo('initiative'),
```

This comment posted in April https://github.com/dockyard/ember-easyForm/issues/126 says that for "nested/embedded objects the error handling in easyForm is unable to bind to errors on nested model objects." Not sure if that adds any insight...

**Comment by oliverbarnes** [comment]
> About passing an object to the submit action, do you mean doing something like object.save() as in this example https://gist.github.com/aloysius-lim/c793c1383fb17e3f4410 line 103?

I mean passing that object as an argument to the action (like on your example's [line 100](https://gist.github.com/aloysius-lim/c793c1383fb17e3f4410#file-app-js-L100))

``` javascript
actions: {
     submit: function(initiative) { 
       ...
       initiative.save()
```

> By nested models, do you mean models that both belongTo each other?

Yes, and in that comment they discussing handling errors, but don't actually show how it's done. I've asked around on issues and IRC, but no luck.

So far I got it working, but now have to find a way to validate the issue object. It's on our, well, [issue list](https://github.com/oliverbarnes/participate-frontend/issues/32) ;)

**Comment by KatiRG** [comment]
oh, ok! thanks.

**Pull request merged**
