### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by KatiRG**
;)

### CODE REVIEW

**Comment by oliverbarnes** [comment]
heheh excellent!  Maybe also add a 'Contributors' section at the end of the README, with your names and links to your github profiles?

**Comment by KatiRG** [comment]
sure!

**Comment by oliverbarnes** [comment]
thanks, will leave this open until this PR is updated with the readme changes

**Comment by oliverbarnes** [comment]
:+1:

**Pull request merged**
