### PR TITLE
Resolved duplication of suggestion in Ember Data

### PR DESCRIPTION
**Pull request by KatiRG**
The code in SuggestionsNewRoute submit action now only stores one record for each suggestion made. The code came from what locks said in the comments for PR 33 https://github.com/oliverbarnes/participate-frontend/pull/33.

We are now reworking the Delete action since we found that it does not actually delete the record, but we are making progress, so stay tuned...

### CODE REVIEW

**Comment by oliverbarnes** [comment]
Great, just waiting on the test.

**Comment by KatiRG** [comment]
The fix to the duplicate suggestion has been incorporated into the delete suggestion PR (#66) and the tests are passing.

**Comment by oliverbarnes** [comment]
will still need a test for this specific bug.

**Comment by KatiRG** [comment]
I don't understand what you want me to test: that there is only one fixture
id created with each suggestion? If I understood you correctly previously,
our code is not supposed to have Ember Data-related code in it?

**Comment by oliverbarnes** [comment]
It's not ember-data-specific, it's just a test going through the steps you took before which showed duplication of suggestions, and asserting that there's no duplication. It's a fundamental practice for when bugs are found: add a test replicating it, then fix it, and submit the fix with the test. This way, if this bug crops again for some reason, the test will ensure there's no regression.

If this is not clear even after me explaining a couple of times, please discuss with the coaches, or with @drogus.

**Comment by KatiRG** [comment]
Sorry, I guess I didn't explain what we found. There were no steps that
showed the duplication of suggestions. We found the duplication simply by
looking at the Ember Data records in the debugger. If we didn't look at the
Ember Data records in the debugger, we could not tell that there were two
suggestions being stored with sequential fixture-x ids. There was no
duplication in the template. We did not see two suggestions appear anywhere.

**Comment by oliverbarnes** [comment]
You can test for duplicate records outside of the template, by checking what's stored before saving a suggestion, and what's stored after that. Testing the number of records is ok and pretty common. There's some confusion here about "testing ember-data" or having "ember-data related code": testing ember-data would mean testing something that the library is responsible for testing internally, whereas testing number of records is part of the application behavior (you can test this regardless of what we're using for saving data). Even if the bug is in a library, testing for number of records ensures the application is working as whole (app + lib).

So it's really testing the data in the application, not Ember Data (the library) itself. 

About "ember-data related code", it's fixtures that shouldn't be referred to directly in implementation code (implementation as opposed to tests). Fixtures are just a tool in Ember Data, that get used in tests and development only (not in production). Testing data is different from testing fixtures.

But let's end this thread here, it's gone way too long. It's the kind of miscommunication that having active coaches should solve, really. But I'll stop complaining :) Don't worry about adding the test, let's move on.

**Pull request closed without merging**
