### PR TITLE
WIP Proposal creation

### PR DESCRIPTION
**Pull request by BernardTolosajr**

### CODE REVIEW

**Comment by oliverbarnes** [comment]
Hey @BernardTolosajr, thanks for the pull request! I will review it later today. One question - is your test suite passing? Need to work out what's going on with travis

**Comment by oliverbarnes** [comment]
So, looks like this is pretty much work in progress. I went ahead and merged your commit to the branch (through the command-line), but in the future, please send PRs once a feature is complete and tests are passing.  This is my bad too, as when I scrapped the old project, the README and CONTRIBUTING guide went with it. I'll commit them back in shortly.

I'm keeping this PR open as WIP, feel free to keep pushing to it and I'll review them. Welcome to the project!

**Comment by oliverbarnes** [comment]
I've pushed the [contributing guide](https://github.com/oliverbarnes/participate/blob/master/CONTRIBUTING.md) and [readme](https://github.com/oliverbarnes/participate/blob/master/README.md) to the upstream proposal-creation branch.

**Comment by BernardTolosajr** [comment]
Hi @oliverbarnes my bad, just having a weird stuff with the pretender, or just me missing something. 

By the way what is the best way to do after the user successfully created a proposal? should we transition to a list of proposal?

**Comment by oliverbarnes** [comment]
Closing this for now, as the discussion continued on slack and the upstream branch is now ahead of the PR.

**Pull request closed without merging**
